### ISSUE TITLE
Issue in cookie based tech detection

### ISSUE THREAD

**Issue by stikhun** [projectdiscovery/wappalyzergo#10]
Sorry for my bad english, using google translate.

defines only if the fingerprint is immediately after Set-Cookie:
eg (Set-Cookie:[laravel_session=)
but if somewhere in the middle, such as (Set-Cookie:[XSRF-TOKEN=*; expires=*, ...; ...; path=/ laravel_session=eyJ*;)
then no longer defines

example domains:
hit4central.com
shcherbyna-advocat.com
amiguiec.xyz
hiom.in
puncbimsi.cf
suzuki.com.pl

**Comment by ehsandeep** [comment]
@stikhun this issue is already fixed in the [past](https://github.com/projectdiscovery/wappalyzergo/pull/8), here is working example with changed position of the cookie value :- https://go.dev/play/p/2o2eWLGRhN4

![image](https://user-images.githubusercontent.com/8293321/151931759-7282ff51-54dc-41ad-a58f-42632eef4a41.png)

There is another possible bug that causing to miss valid tech that needs to explored futher, for example: 

```
echo shcherbyna-advocat.com | httpx -td
```
results into
```
http://shcherbyna-advocat.com [Google Font API,Google Tag Manager,Lightbox,LiteSpeed,PHP]
```
with missing `Laravel` in output.

**Comment by stikhun** [comment]
70% of sites have cookies in this format: path=/  laravel_session=
https://go.dev/play/p/sQ7ygwFHEnd

**Comment by ehsandeep** [comment]
I see what you mean, thanks for sharing the additonal info.

**Comment by ehsandeep** [comment]
@stikhun this is now fixed with https://github.com/projectdiscovery/wappalyzergo/pull/11
